console.log("We are learning strings.");
let n="Javascript";
console.log(n[0]);
console.log(n[1]);
console.log(n[2]);
console.log(n[3]);
console.log(n[4]);
console.log(n[5]);
console.log(n[6]);
console.log(n[7]);
console.log(n[8]);
console.log(n[9]);
console.log(n.length);
